# Generated by Django 5.2.6 on 2026-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
