# Generated by Django 6.0.1 on 2026-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_alter_photo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
